baseURL = "https://anujkhare.github.io/"
languageCode = "en-us"
title = "Anuj Khare"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "Projects"
    URL = "portfolio"
    weight = 2

    # [[menu.nav]]
    # name = "Blog"
    # URL = "blog"
    # weight = 7

# Site params
[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-m0gnUBkjmhoQyNyd7nllA"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    # bgImage = "images/slider/hero-area.jpg"
    # icon = "tf-ion-play"
    heading = "Anuj Khare"
    content = "I am a Machine Learning engineer and a kick-ass software developer. I am enthusiastic about yoga, travel, and music. This is my space!"
    btn = true
    btnText="Explore My Work"
    btnURL="#portfolio"

    
    # social Icons
    [params.socialmedia]
        [[params.socialmedia.socialIcon]]
        icon = "tf-ion-email"
        url = "mailto:khareanuj18@gmail.com"
        
        [[params.socialmedia.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "https://www.linkedin.com/in/anuj-khare-72942498/"
        
        [[params.socialmedia.socialIcon]]
        icon = "tf-ion-social-github"
        url = "https://github.com/anujkhare/"

        [[params.socialmedia.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/anujk18"
